# Generated by Django 2.2.7 on 2019-12-05 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('score', models.CharField(default='语文', max_length=20)),
                ('c_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('c_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加日期')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Teacher')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
